language: perl
sudo: false
dist: trusty

install:
  - perlbrew list
  - cpanm -n Dist::Zilla
  - cpanm -n App::af
  - cpanm -n Alien::Build::Plugin::Probe::OverrideCI
  - af missing --precompile   | cpanm -n
  - af missing --plugin       | cpanm -n
  - af missing                | cpanm -n
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

env:
  global:
    - ALIEN_BUILD_PRELOAD=Probe::OverrideCI
  matrix:
    - ALIEN_INSTALL_TYPE_CI=share
    - ALIEN_INSTALL_TYPE_CI=system

script:
  - dzil test -v
